'use strict';
const $ = s => document.querySelector(s);
const escapeHTML = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lineages = [
 {name:'ln_bwd',title:'LayerNorm backward',latency:84.2,delta:31,seed:'Inductor + Liger'},
 {name:'fused_gelu_mlp',title:'GELU–MLP epilogue',latency:412,delta:24,seed:'Triton tutorial matmul'},
 {name:'ema_update',title:'EMA target update',latency:41.9,delta:18,seed:'Inductor + handwritten'},
 {name:'masked_gather',title:'Masked gather + position',latency:203,delta:0,seed:'Inductor'}
];
const strategies=['Keep reduction partials in registers, single pass','Fuse GELU into the matmul epilogue, 128 × 128 tile','Vectorize the update with eight elements per thread','Coalesce index loads and add positional embeddings'];
let state;
function reset(){state={gen:7,tick:0,seconds:272,paused:false,step:128.7,spend:2.84,nextId:160,history:[180,168.4,164.8,151.3,151.3,140.2,133.9,128.7],rows:[]};for(let i=0;i<24;i++){const k=i%4;state.rows.push({id:`cand_${String(135+i).padStart(4,'0')}`,lineage:lineages[k].name,strategy:strategies[k],gates:i%4===0?4:1+i%3,accepted:i%4===0,gen:Math.floor(i/4)+1,step:i%4===0?(179-i*2.187).toFixed(1):null});}state.rows.push({id:'cand_0159',lineage:'fused_gelu_mlp',strategy:strategies[1],gates:2,running:true,gen:7});if($('#model').value==='lm')state.rows=state.rows.filter(r=>['ln_bwd','fused_gelu_mlp'].includes(r.lineage));render();}
function setView(view){for(const name of ['overview','archive','lessons'])$(`#${name}-view`).hidden=name!==view;document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});}
function gates(row){return [1,2,3,4].map(g=>{const cls=g<row.gates?'pass':g===row.gates?(row.running?'running':row.accepted?'pass':'fail'):'';return `<td><span class="gate ${cls}" aria-label="Gate ${g}: ${cls==='pass'?'passed':cls==='fail'?'failed':cls==='running'?'running':'not reached'}">${cls==='pass'?'✓':cls==='fail'?'×':cls==='running'?'···':'—'}</span></td>`}).join('');}
function outcome(row){return row.running?`Gate ${row.gates} running`:row.accepted?'Accepted':['','Compile failed','Grad mismatch','Not faster','No in-model win'][row.gates];}
function rowHTML(row){return `<tr><td><button class="candidate" data-candidate="${row.id}">${row.id} ↗</button><small>${escapeHTML(row.strategy)}</small></td><td class="mono">${row.lineage}</td>${gates(row)}<td class="outcome ${row.running?'':row.accepted?'accepted':'failed'}">${outcome(row)}</td></tr>`;}
function renderChart(){const points=state.history.map((v,i)=>[48+i*624/Math.max(10,state.history.length-1),20+(185-v)*1.85]);const path=points.map((p,i)=>`${i?'H '+p[0]+' V':'M '+p[0]} ${p[1]}`).join(' ');const last=points.at(-1);$('#chart').innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#008596" stop-opacity=".14"/><stop offset="1" stop-color="#008596" stop-opacity="0"/></linearGradient></defs>${[180,150,120,90].map(n=>`<line x1="48" x2="694" y1="${20+(185-n)*1.85}" y2="${20+(185-n)*1.85}" stroke="#dfe3d9" ${n===180?'stroke-dasharray="4 4"':''}/><text x="0" y="${24+(185-n)*1.85}" fill="#73796e" font-size="11" font-family="monospace">${n} ms</text>`).join('')}<path d="${path} L ${last[0]} 214 L 48 214 Z" fill="url(#fill)"/><path d="${path}" stroke="#007e91" stroke-width="2.5" fill="none"/>${points.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="#fffefa" stroke="#007e91" stroke-width="1.5"/>`).join('')}<circle cx="${last[0]}" cy="${last[1]}" r="5" fill="#007e91"/><text x="${Math.min(last[0]+10,640)}" y="${last[1]-12}" fill="#007e91" font-size="12" font-family="monospace">${state.step.toFixed(1)} ms</text>${points.filter((_,i)=>i%2===0).map(p=>`<text x="${p[0]}" y="232" fill="#73796e" font-size="11" font-family="monospace">${points.indexOf(p)}</text>`).join('')}`;}
function renderArchive(){const query=$('#search').value.toLowerCase(),filter=$('#filter').value;const rows=state.rows.filter(r=>(filter==='all'||(filter==='accepted'?r.accepted:!r.accepted&&!r.running))&&`${r.id} ${r.lineage} ${r.strategy}`.toLowerCase().includes(query));$('#archive-rows').innerHTML=rows.slice().reverse().map(rowHTML).join('');$('#empty').hidden=rows.length>0;}
function render(){document.body.classList.toggle('paused',state.paused);$('#pause').textContent=state.paused?'▶ Resume replay':'Ⅱ Pause replay';$('#status').textContent=state.gen>=50?'Replay complete':state.paused?'Replay paused':'Search in progress';$('#generation').textContent=state.gen;$('#elapsed').textContent=`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`;$('#step').textContent=state.step.toFixed(1);$('#improvement').textContent=`−${((1-state.step/180)*100).toFixed(1)}%`;$('#speedup').textContent=`${(180/state.step).toFixed(2)}× faster`;$('#mfu').textContent=(38.2*128.7/state.step).toFixed(1);$('#accepted').textContent=state.rows.filter(r=>r.accepted).length;$('#evaluated').textContent=`/ ${state.rows.filter(r=>!r.running).length}`;$('#archive-count').textContent=state.rows.length;$('#spend').textContent=state.spend.toFixed(2);$('#budget-bar').style.width=`${state.spend/20*100}%`;$('#live-rows').innerHTML=state.rows.slice(-5).reverse().map(rowHTML).join('');const phase=state.tick%12<2?0:state.tick%12<4?1:state.tick%12<9?2:state.tick%12<11?3:4;$('#phase-label').textContent=['PLANNER · PROPOSING','SUBAGENTS · IMPLEMENTING','VERIFIER · CHECKING','ARCHIVE · SELECTING','CURATOR · LEARNING'][phase];$('#pipeline').innerHTML=[['Plan','Diverse strategies'],['Implement','Parallel candidates'],['Verify','Four deterministic gates'],['Select','Keep verified survivors'],['Learn','Lessons feed forward']].map((s,i)=>`<div class="stage ${i===phase?'active':''}"><span class="mono">0${i+1} ${i===phase?' / ACTIVE':''}</span><strong>${s[0]}</strong><small>${s[1]}</small></div>`).join('');$('#lineages').innerHTML=lineages.filter(l=>$('#model').value==='jepa'||['ln_bwd','fused_gelu_mlp'].includes(l.name)).map((l,i)=>`<article class="lineage"><span class="number">0${i+1}</span><button data-lineage="${l.name}">${l.title} ↗</button><p>${l.seed}</p><div class="bar"><span style="width:${l.delta||2}%"></span></div><p><strong>${l.latency} µs</strong> <span style="float:right;color:var(--cyan)">${l.delta?'−'+l.delta+'%':'Seed unbeaten'}</span></p></article>`).join('');$('#lessons').innerHTML=[['06','Keep dgamma and dbeta partials in registers. The single-pass LayerNorm strategy passed all four gates.'],['05','Fusion must win in the model. An isolated speedup can disappear once the kernel is swapped into the training step.'],['04','Avoid hardcoded dimensions. Candidates must match outputs and gradients on the unseen shape as well as observed shapes.'],['03','Keep correct but slower strategies in the diversity pool; they may become useful fusion parents.']].map(([gen,text])=>`<article class="lesson"><span class="mono muted">GENERATION ${gen}</span><p>${text}</p></article>`).join('');renderChart();renderArchive();}
function advance(){if(state.paused||state.gen>=50)return;state.seconds++;state.tick++;if(state.tick%3===0){let row=state.rows.at(-1);if(row.running&&row.gates<4){row.gates++;}else if(row.running){row.running=false;row.accepted=state.rows.length%3===1;if(row.accepted){state.step=Math.max(91,state.step-1.1);row.step=state.step.toFixed(1);}}else{const k=state.rows.length%($('#model').value==='lm'?2:4);state.rows.push({id:`cand_${String(state.nextId++).padStart(4,'0')}`,lineage:lineages[k].name,strategy:strategies[k],gates:1,running:true,gen:state.gen});state.spend+=.08;}}if(state.tick%12===0){state.gen++;state.history.push(state.step);}if(state.gen>=50){state.paused=true;const row=state.rows.at(-1);if(row.running)state.rows.pop();}render();}
function detail(id){const r=state.rows.find(r=>r.id===id);if(!r)return;$('#detail-body').innerHTML=`<h2>${r.id}</h2><span class="mono muted">${r.lineage} · Generation ${r.gen} · demo evidence</span><p>${escapeHTML(r.strategy)}</p><div class="evidence">${['Compile','Correctness','Isolated speed','In-model speed'].map((g,i)=>`<div>0${i+1} ${g}<strong>${i+1<r.gates?'Passed':i+1===r.gates?(r.running?'Running':r.accepted?'Passed':'Rejected'):'Not reached'}</strong></div>`).join('')}</div><h3>${outcome(r)}</h3><p>${r.running?'This candidate is moving through the deterministic verifier.':r.accepted?`Matched outputs and gradients on three observed shapes and one unseen shape. Training step: ${r.step} ms.`:['','Triton JIT compilation failed. Compiler feedback is returned to the repair loop.','Gradient comparison exceeded calibrated tolerance. This candidate cannot enter the accepted archive.','The isolated benchmark did not clear the calibrated 3% margin.','The in-model benchmark did not clear the calibrated 1% margin.'][r.gates]}</p><pre>Reference: eager PyTorch\nDtype: bf16 · rtol 1e-2 · atol 1e-2\nTiming: synchronized CUDA events\nGate 3: median of 50 measurements\nGate 4: 10 warmup + 30 timed steps</pre><p>Source code and Weave trace links will appear here when a real archive is connected.</p>`;$('#detail').showModal();}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const candidate=e.target.closest('[data-candidate]');if(candidate)detail(candidate.dataset.candidate);const lineage=e.target.closest('[data-lineage]');if(lineage){$('#search').value=lineage.dataset.lineage;$('#filter').value='all';renderArchive();setView('archive');}if(e.target.closest('.close'))e.target.closest('dialog').close();});
$('#pause').addEventListener('click',()=>{if(state.gen>=50)reset();else{state.paused=!state.paused;render();}});$('#replay').addEventListener('click',reset);$('#search').addEventListener('input',renderArchive);$('#filter').addEventListener('change',renderArchive);$('#model').addEventListener('change',()=>{reset();if($('#model').value==='lm'){state.rows=state.rows.filter(r=>['ln_bwd','fused_gelu_mlp'].includes(r.lineage));}$('#run-name').textContent=$('#model').value==='lm'?'LM–003':'JEPA–007';render();});$('#new-run').addEventListener('click',()=>$('#setup').showModal());$('#setup-form').addEventListener('submit',e=>{e.preventDefault();const name=new URL($('#repo').value).pathname.split('/').filter(Boolean).at(-1)||'DEMO';reset();$('#run-name').textContent=name.toUpperCase()+'–DEMO';$('#setup').close();setView('overview');});$('#export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({demo:true,model:$('#model').value,generation:state.gen,candidates:state.rows},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='kernel-evolution-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});reset();setInterval(advance,1000);

// Review canvas: each frame opens a stable UI state independently.
const previewView = new URLSearchParams(location.search).get('preview');
if (previewView) {
  state.paused = true;
  render();
  if (['overview', 'archive', 'lessons'].includes(previewView)) setView(previewView);
  if (previewView === 'setup') $('#setup').showModal();
  if (previewView === 'candidate') detail(state.rows.find(r => r.accepted).id);
}

const submittedRepo = new URLSearchParams(location.search).get("repo");
if (submittedRepo) {
  try {
    const repoURL = new URL(submittedRepo);
    $("#run-name").textContent = (repoURL.pathname.split("/").filter(Boolean).at(-1) || "REPO").toUpperCase() + "–DEMO";
  } catch {}
}

const submittedData = new URLSearchParams(location.search).get('data');
if (submittedData) {
  try {
    const dataURL = new URL(submittedData);
    const source = document.querySelector('#run-data-source');
    if (source) { source.hidden = false; source.textContent = 'DATA / ' + dataURL.hostname + dataURL.pathname; }
  } catch {}
}
